# Generated by Django 4.2.1 on 2023-05-29 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Iq_Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iqtest',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='iqtest',
            name='student',
        ),
        migrations.AddField(
            model_name='iqtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iqtest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iqtest',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iq_Test.iqtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('pattern_image', models.ImageField(blank=True, null=True, upload_to='question_patterns/')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iq_Test.iqtest')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iq_Test.question')),
            ],
        ),
    ]
