# Generated by Django 4.2.1 on 2023-05-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('course_structure', models.TextField()),
                ('Admission_Requirement', models.TextField()),
                ('Feestructure', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100, null=True)),
                ('Second_name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('Service_no', models.CharField(max_length=100, null=True)),
                ('Id_no', models.IntegerField()),
                ('Qualifications', models.FileField(upload_to='')),
                ('Adress', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Courses', models.ManyToManyField(to='Departments.courses')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Departments.profile')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department'),
        ),
    ]
