# Generated by Django 4.2.1 on 2023-05-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('service_no', models.CharField(max_length=100, null=True)),
                ('id_no', models.IntegerField()),
                ('qualifications', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Admission_Requirement',
            new_name='admission_requirement',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Feestructure',
            new_name='fee_structure',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='Departments.courses'),
        ),
        migrations.AddField(
            model_name='students',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Departments.profiles'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.students'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
