# Generated by Django 4.2.1 on 2023-05-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_profiles_students_rename_department_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='courses',
            new_name='course',
        ),
    ]
