# Generated by Django 4.2.1 on 2023-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_rename_courses_students_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='', upload_to='Department_pics'),
        ),
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(default='', upload_to='Department_pics'),
        ),
    ]
