# Generated by Django 4.2.1 on 2023-05-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0004_courses_image_departments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='student',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile',
        ),
    ]
