# Generated by Django 4.2.1 on 2023-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0005_remove_profiles_student_remove_students_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='news_pics')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('puplish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
