# Generated by Django 4.2.1 on 2023-05-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0006_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
