# Generated by Django 4.2.1 on 2023-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Question',
            field=models.TextField(),
        ),
    ]
