# Generated by Django 4.2.1 on 2023-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0009_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('pysical_address', models.TextField()),
                ('Electronic_Address', models.TextField()),
            ],
        ),
    ]
