# Generated by Django 4.2.1 on 2023-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0010_location_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisionAndValues', models.TextField()),
                ('Our_Qualities', models.CharField(max_length=100)),
                ('History', models.TextField()),
            ],
        ),
    ]
