# Generated by Django 4.2.1 on 2023-05-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Departments', '0014_students_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departments.courses'),
        ),
    ]
