# Generated by Django 4.2.1 on 2023-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0015_remove_students_course_alter_students_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
