# Generated by Django 4.2.1 on 2023-05-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0016_alter_students_id_no_alter_students_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='student',
        ),
        migrations.AlterField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departments.departments'),
        ),
    ]
