# Generated by Django 4.2.1 on 2023-05-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0018_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Departments.courses'),
        ),
    ]
